version: "3"
services:
  mysql:
    container_name: mysql
    platform: linux/x86_64
    build: ./web-services-db/database/mysql/
    ports:
      - "3306:3306"
    volumes:
      - ./web-services-db/database/mysql/db:/docker-entrypoint-initdb.d
      - ./web-services-db/database/mysql/conf.d:/etc/mysql/conf.d
    env_file:
      - web-services-db/database/mysql/local.env
    tty: true
  fastapi-authentication:
    depends_on:
      - mysql
    container_name: fast_api
    platform: linux/x86_64
    build:
      context: ./fastapi-authentication
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    volumes:
      - ./fastapi-authentication:/app
    ports:
      - 8000:8000
    env_file:
      - ./fastapi-authentication/local.env