version: "3"
services:
  mysql-user-db:
    container_name: mysql-user-db
    platform: linux/x86_64
    build: ./database/web-services-user-db/database/mysql/
    ports:
      - "3306:3306"
    volumes:
      - ./database/web-services-user-db/database/mysql/db:/docker-entrypoint-initdb.d
      - ./database/web-services-user-db/database/mysql/conf.d:/etc/mysql/conf.d
    env_file:
      - database/web-services-user-db/database/mysql/local.env
    tty: true
  mysql-music-db:
    container_name: mysql-music-db
    platform: linux/x86_64
    build: ./database/music-db/database/mysql/
    ports:
      - "3308:3306"
    volumes:
      - ./database/music-db/database/mysql/db:/docker-entrypoint-initdb.d
      - ./database/music-db/database/mysql/conf.d:/etc/mysql/conf.d
    env_file:
      - database/music-db/database/mysql/local.env
    tty: true
  music-app:
    depends_on:
      - mysql-user-db
      - mysql-music-db
    container_name: fast_api
    platform: linux/x86_64
    build:
      context: ./backend/musicApp
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    volumes:
      - ./backend/musicApp:/app
    ports:
      - "8000:8000"
    env_file:
      - ./backend/musicApp/local.env
  id3-app:
    depends_on:
      - mysql-user-db
      - mysql-music-db
    container_name: fast_api_id3
    platform: linux/x86_64
    build:
      context: ./backend/id3-service
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    volumes:
      - ./backend/id3-service:/app
    ports:
      - "8001:8000"